apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: chandrushane/flask-products
        env:
          - name: USERS_SERVICE
            values: users
          
          - name: ORDERS_SERVICE
            values: orders

        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: products
spec:
  selector:
    app: products
  ports:
  - protocol: TCP
    port: 5000 # outside facing port
    targetPort: 5000 # container exposed port
    
