"""empty message

Revision ID: 50240031140e
Revises: 4ffbc81180d4
Create Date: 2024-03-16 19:00:51.813463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50240031140e'
down_revision = '4ffbc81180d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=True))
        batch_op.drop_constraint('products_description_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_unique_constraint('products_description_key', ['description'])
        batch_op.drop_column('version')

    # ### end Alembic commands ###
