global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask-products'
    static_configs:
      - targets: ['products:5000']  # Adjust based on your Flask service names and ports

  - job_name: 'flask-users'
    static_configs:
      - targets: ['users:5000']

  - job_name: 'flask-orders'
    static_configs:
      - targets: ['orders:5000']