name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build product --tag chandrushane/flask-products:latest
        echo $DOCKER_KEY | docker login --username $DOCKER_USERNAME
        docker push chandrushane/flask-products:latest
