name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_KEY: ${{ secrets.DOCKER_KEY }}
        DOCKER_TEST: ${{ secrets.DOCKER_TEST }}

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo manualtesting
        echo $DOCKER_USERNAME
        echo closing
        docker build product --tag chandrushane/flask-products:latest
        echo $DOCKER_KEY | docker login --username $DOCKER_USERNAME --password-stdin 
        docker push chandrushane/flask-products:latest
    
